### PR TITLE
Add DefaultBits, overwriting Default to fix its semantics

### LINKED ISSUE #50: `#[derive(Default)` introduces unsoundness in structs
you can `#[derive(Default)]` on bitsized structs, since `arbitray_int::UInt` is `Default`. this has the same effect as setting the inner value to `0`. this can introduce unsoundness:

```rust
use bilge::prelude::*;

#[bitsize(2)]
#[derive(TryFromBits, Debug)]
enum Unfilled {
    A = 1,
    B = 2,
    C = 3,
}

#[bitsize(2)]
#[derive(TryFromBits, Default, DebugBits)]
struct Unsound {
    field1: Unfilled,
}

fn main () {
    let via_try_from = Unsound::try_from(u2::new(0));
    assert!(via_try_from.is_err());
    
    let via_default = Unsound::default(); // via_default.field1 is now a value of `Unfilled` that is not allowed
    dbg!(via_default); // this crashes at runtime (panicked at 'unreachable')
}
```

### PR DESCRIPTION
**Pull request by hecatia-elegua**
Closes #50.
Taking @pickx example to explain this again, but slightly different:
```rust
#[bitsize(1)]
#[derive(Default, FromBits)]
enum HasDefault {
    A, 
    #[default]
    B
}

#[bitsize(1)]
#[derive(Default, FromBits)]
struct Foo {
    has_def: HasDefault
}
```
Here, `HasDefault::default()` would be 1.
But `Foo` is expanded like this:
```rust
#[derive(Default)]
struct Foo { value: u1 };
```
which will generate `Foo { value: 0 }` as the default, which is wrong.
Since it is completely wrong, we will now just silently change `Default` to be `DefaultBits`.

I feel like `DebugBits` should do the same. Or not `abort`.
You either want deep debugging with `DebugBits` or just want some number telling you the internal state, which `Debug` would still do.

### CODE REVIEW

File: bilge-impl/src/bitsize/split.rs [hunk 1]
```diff
@@ -70,13 +70,16 @@ impl SplitAttributes {
...
                 ParsedAttribute::DeriveList(derives) => {
-                    for derive in derives {
+                    for mut derive in derives {
                         if derive.matches(&["zerocopy", "FromBytes"]) {
                             from_bytes = Some(derive.clone());
                         } else if derive.matches(&["bilge", "FromBits"]) {
                             has_frombits = true;
                         } else if derive.matches_core_or_std(&["fmt", "Debug"]) && is_struct {
                             abort!(derive.0, "use derive(DebugBits) for structs")
+                        } else if derive.matches_core_or_std(&["fmt", "Default"]) && is_struct {
```
[the remark this answers is not in the document]
Comment (pickx) [reply bilge-impl/src/bitsize/split.rs:80]: the fact that the test worked is a happy accident

**Review by pickx — CHANGES_REQUESTED** [review]

File: src/lib.rs [hunk 2]
```diff
@@ -33,7 +33,7 @@ pub unsafe trait Filled: Bitsized {}
 unsafe impl<T> Filled for T where T: Bitsized + From<<T as Bitsized>::ArbitraryInt> {}
 
 /// This is generated to statically validate that a type implements `FromBits`.
-pub fn assume_filled<T: Filled>() {}
+pub const fn assume_filled<T: Filled>() {}
```
Comment (pickx) [inline src/lib.rs:36]: nice

File: bilge-impl/src/default_bits.rs [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+                    i += 1;
+                }
+                acc
+            }}
+        },
+        Path(path) => {
+            let field_size = shared::generate_type_bitsize(ty);
+            // u2::from(HaveFun::default()).value() as u32;
+            quote! {{
+                let as_int = <#path as Bitsized>::ArbitraryInt::from(#path::default()).value();
```
Comment (pickx) [inline bilge-impl/src/default_bits.rs:64]: if `#path` does not implement `Default`, we get "no variant or associated item named `default` found for...". and unfortunately the span for this error is the `#[bitsize(...)]` attribute.

to make this message match the one generated by `std`'s `#[derive(Default)]`, we can add `assume_default<#path>()` here. unfortunately if this was, say, a tuple, this would generate a message for each element (with duplicates). AND the original "no variant or associated item" is still generated.

might be possible to generate the assert for each field of the original struct instead. I don't know if any of this even matters.

**Review by pickx — CHANGES_REQUESTED** [review]
looks pretty good overall

File: bilge-impl/src/default_bits.rs (hunk 3 above)
Comment (hecatia-elegua) [reply bilge-impl/src/default_bits.rs:64]: says "the following trait defines an item `default`, perhaps you need to implement it" on my end, but we can fix this even more:
`<#path as ::core::default::Default>::default()`
-> "the trait bound `HaveFun: std::default::Default` is not satisfied
the trait `std::default::Default` is not implemented for `HaveFun`"

File: bilge-impl/src/default_bits.rs [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+}
+
+fn generate_default_inner(ty: &Type) -> TokenStream {
+    use Type::*;
+    match ty {
+        // TODO?: we could optimize nested arrays here like in `struct_gen.rs`
+        Array(array) => {
+            let len_expr = &array.len;
+            let elem_ty = &*array.elem;
+            // generate the default value code for one array element
```
[the remark this answers is not in the document]
Comment (hecatia-elegua) [reply bilge-impl/src/default_bits.rs:44]: interesting, we should note that at least

File: bilge-impl/src/bitsize/split.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (hecatia-elegua) [reply bilge-impl/src/bitsize/split.rs:80]: oops

File: bilge-impl/src/default_bits.rs (hunk 3 above)
Comment (pickx) [reply bilge-impl/src/default_bits.rs:64]: oh, beautiful.

**Review by pickx — APPROVED** [review]
